to retrieve country by its country code
nittin-shankar/country-finder pull request #5
Opened 2023-06-22 08:19 UTC by Vishal-progammer

2023-06-22 08:33 UTC, nittin-shankar requested changes
Good job @Vishal-progammer. Very happy that you completed it. I just have a few changes for you to make.

2023-06-22 08:33 UTC, nittin-shankar commented on config/dev.exs
> +  http: [ip: {127, 0, 0, 1}, port: 4003],
Change this back to 4000

2023-06-22 08:33 UTC, nittin-shankar commented on lib/country_finder/country.ex
> +    :countrycode
Rename this as `country_code`. It's more readable in this way.

2023-06-22 08:33 UTC, nittin-shankar commented on lib/country_finder/country_client.ex
> +    url = "https://restcountries.com/v3.1/all?fields=flags,name,population,region,capital,cca2"
Use `cca3` instead of `cca2`.

2023-06-23 04:37 UTC, Vishal-progammer commented on config/dev.exs
> +  http: [ip: {127, 0, 0, 1}, port: 4003],
done

2023-06-23 04:38 UTC, Vishal-progammer commented on lib/country_finder/country_client.ex
> +    url = "https://restcountries.com/v3.1/all?fields=flags,name,population,region,capital,cca2"
done

2023-07-19 10:47 UTC, closed without merging