Add comma to population and add country code in the api call
nittin-shankar/country-finder pull request #6
Opened 2023-06-28 05:15 UTC by sangeethailango

2023-06-28 05:23 UTC, nittin-shankar requested changes
Good job completing the task. Please take a look at review comments.

2023-06-28 05:23 UTC, nittin-shankar commented on lib/country_finder.ex
> +      country_code = get_in(country_map, ["cca3"])
```suggestion
      country_code = country_map["cca3"]
```
Don't use `get_in` function when it is not listed

2023-06-28 05:23 UTC, nittin-shankar commented on lib/country_finder.ex
> +  def add_comma(integer) do
Good job writing the function here 💯

2023-06-28 05:23 UTC, nittin-shankar commented on lib/country_finder.ex
> +      population = add_comma(country_map["population"])
In the struct, store it just as an integer. Use the function in template. Also, it'll be better if rename the function from `add_comma` to `format_population`. Write some documentation for the function too.

2023-06-28 06:07 UTC, sangeethailango commented on lib/country_finder.ex
> +      country_code = get_in(country_map, ["cca3"])
Done

2023-06-28 06:13 UTC, sangeethailango commented on lib/country_finder.ex
> +      population = add_comma(country_map["population"])
Can i write documentation above the function, using @doc?

2023-06-28 06:14 UTC, nittin-shankar commented on lib/country_finder.ex
> +      population = add_comma(country_map["population"])
Yes, please do that!!

2023-06-28 06:15 UTC, nittin-shankar requested changes
@sangeethailango Before, you push other changes. Please format the code and push it.

2023-07-05 06:01 UTC, nittin-shankar requested changes
Good attempt in writing the documentation. But it could be even better!!!

2023-07-05 06:01 UTC, nittin-shankar commented on lib/country_finder.ex
> +     Integer.to_charlist() -> Converting integer to charlist as Enum.reverse expects list of intger.
We don't need this much additional information on the documentation. You're formatting it with a separator called **thousands seperator**. Just something like:
_Formats the given integer with thousands separator._

And you can also provide with a few examples as to how this function works. Have you seen there are examples of almost all functions in the `Enum` module. Examples allow for better grasping.

2023-07-17 10:14 UTC, nittin-shankar approved these changes
Good job but I'll be closing this PR as I merged PR of @kodi6

2023-07-17 10:14 UTC, closed without merging